- name: Creating a file with content
  copy:
    dest: "/home/{{USERNAME}}/bootcamp-app/.env"
    content: |
       #Host configuration
       PORT=8080
       HOST=0.0.0.0
       NODE_ENV=development
       HOST_URL=http://{{LB_PORT}}:8080
       COOKIE_ENCRYPT_PWD=superAwesomePasswordStringThatIsAtLeast32CharactersLong!

       # Okta configuration
       OKTA_ORG_URL={{OKTA_ORG_URL}}
       OKTA_CLIENT_ID={{OKTA_CLIENT_ID}}
       OKTA_CLIENT_SECRET={{OKTA_CLIENT_SECRET}}

       # Postgres configuration
       PGHOST={{PGHOSTNAME}}
       PGUSERNAME={{PGUSERNAMEE}}
       PGDATABASE=postgres
       PGPASSWORD={{PGPASS}}
       PGPORT=5432
